services:
  user-microservice:
    build: ./user-microservices
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - userdb

  userdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

  hotel-microservice:
    build: ./hotel-microservice
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://hoteldb:3306/hotel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - hoteldb

  hoteldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: hotel_db
    ports:
      - "3308:3306"

  reservation-microservice:
    build: ./reservation-microservices
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://resrvationdb:3306/reservation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - resrvationdb

  resrvationdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: reservation_db
    ports:
      - "3309:3306"

  restaurant-microservice:
    build: ./restaurant-microservice
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://restaurantdb:3306/restaurant_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - restaurantdb

  restaurantdb:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: example_psw
        MYSQL_DATABASE: restaurant_db
      ports:
        - "3310:3306"

  order-microservice:
      build: ./order-microservice
      ports:
        - "8085:8080"
      environment:
        SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
        SPRING_DATASOURCE_URL: jdbc:mysql://orderdb:3306/order_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: example_psw
      depends_on:
        - orderdb

  orderdb:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: example_psw
        MYSQL_DATABASE: order_db
      ports:
        - "3311:3306"

  feedback-microservice:
      build: ./feedback-microservice
      ports:
        - "8088:8080"
      environment:
        SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
        SPRING_DATASOURCE_URL: jdbc:mysql://feedbackdb:3306/feedback_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: example_psw
      depends_on:
        - feedbackdb

  feedbackdb:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: example_psw
        MYSQL_DATABASE: feedback_db
      ports:
        - "3312:3306"

  payroll-microservice:
      build: ./payroll-microservice
      ports:
        - "8089:8080"
      environment:
        SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
        SPRING_DATASOURCE_URL: jdbc:mysql://payrolldb:3306/payroll_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: example_psw
      depends_on:
        - payrolldb

  payrolldb:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: example_psw
        MYSQL_DATABASE: payroll_db
      ports:
        - "3313:3306"

  report-microservice:
      build: ./reports-microservice
      ports:
        - "8087:8080"
      environment:
        SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
        SPRING_DATASOURCE_URL: jdbc:mysql://reportdb:3306/report_db
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: example_psw
      depends_on:
        - reportdb

  reportdb:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: example_psw
        MYSQL_DATABASE: report_db
      ports:
        - "3314:3306"
