services:
  user-microservice:
    build: ./user-microservices
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - userdb

  userdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

  hotel-microservice:
    build: ./hotel-microservice
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://hoteldb:3306/hotel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - hoteldb

  hoteldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: hotel_db
    ports:
      - "3308:3306"

  reservation-microservice:
    build: ./reservation-microservices
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://resrvationdb:3306/reservation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - resrvationdb

  resrvationdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: reservation_db
    ports:
      - "3340:3306"
