services:
  reservation-microservice:
    build: .
    ports:
      - "8089:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://payrolldb:3306/payroll_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example_psw
    depends_on:
      - payrolldb

  payrolldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_psw
      MYSQL_DATABASE: payroll_db
    ports:
      - "3314:3306"
