services:
  feedback-microservice:
    build: .
    ports:
      - "8088:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activar el perfil docker
      SPRING_DATASOURCE_URL: jdbc:mysql://feedbackdb:3306/feedback_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - feedbackdb

  feedbackdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: feedback_db
    ports:
      - "3314:3306"
